apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'de.infonline.sampleapp'

    compileSdk 33

    defaultConfig {
        applicationId "de.infonline.sampleapp"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName '1.1.1'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig = true
    }
    
    kotlinOptions {
        jvmTarget = "17"
    }

    flavorDimensions = ["endpoint"]

    productFlavors {
        dev {
            dimension "endpoint"
        }

        prod {
            dimension "endpoint"
        }
    }
}

apply from: "credentials.gradle"

repositories {
    maven {
        url "https://repo.infonline.de/api/v4/projects/5/packages/maven"
        name "INFOnline"

        credentials(HttpHeaderCredentials) {
            name = "Private-Token"
            value = project.ext.mavenRepoAccessToken
        }
        authentication {
            header(HttpHeaderAuthentication)
        }
    }
}

dependencies {
    //noinspection GradleDynamicVersion
    implementation 'de.infonline:iomb-library:1.+'

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22"
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    implementation 'io.reactivex.rxjava3:rxjava:3.1.6'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
    implementation 'io.reactivex.rxjava3:rxkotlin:3.0.1'
}
